Repository ehju/SSD_Project_BOYSCOUT, pull requests merged in 2025-07, with the labels that each got.

#91 [add] introcude pull request template documenting
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#94 [add/Refactor] Feature/ssd flush cmd
  SSD_Excutor/command_parser.cpp
  SSD_Excutor/command_parser.h
  SSD_Excutor/command_parser_test.cpp
Labels: Refactor, Green

#96 [add] erase, flush in Shell
  TestShell_Excutor/CommandParser.h
  TestShell_Excutor/ShellCommand.cpp
  TestShell_Excutor/ShellCommand.h
  TestShell_Excutor/ShellCommand_test.cpp
  TestShell_Excutor/TS_function.cpp
  TestShell_Excutor/TS_function.h
  TestShell_Excutor/TestShell_Excutor.vcxproj
Labels: Green, Requirement

#102 [clean] remove unused file(test.cpp)
  TestShell_Excutor/TestShell_Excutor.vcxproj
  TestShell_Excutor/TestShell_Excutor.vcxproj.filters
  TestShell_Excutor/test.cpp
Labels: Clean

#111 [add]TS4 command to parser & add UT for CreateCommandData
  TestShell_Excutor/CommandData.h
  TestShell_Excutor/CommandParser.cpp
  TestShell_Excutor/CommandParser.h
  TestShell_Excutor/CommandParser_test.cpp
Labels: Green

#116 [fix] add calling SSD's flush in Flush::excute
  TestShell_Excutor/ShellFlush.cpp
Labels: Bug
