Repository ehju/SSD_Project_BOYSCOUT, pull requests merged in 2025-08, with the labels that each got.

#124 [add]Proxy Read 기능 개발
  SSD_Excutor/proxyRead.cpp
  SSD_Excutor/proxyRead.h
  SSD_Excutor/proxyRead_test.cpp
Labels: Requirement

#130 [refactor] use Logger.getinstance() as Singleton
  TestShell_Excutor/ShellErase.cpp
  TestShell_Excutor/ShellErase.h
  TestShell_Excutor/ShellEraseRange.cpp
  TestShell_Excutor/ShellEraseRange.h
  TestShell_Excutor/ShellFlush.cpp
  TestShell_Excutor/ShellFlush.h
  TestShell_Excutor/ShellFullRead.cpp
  TestShell_Excutor/ShellFullRead.h
  TestShell_Excutor/ShellFullWrite.cpp
  TestShell_Excutor/ShellFullWrite.h
  TestShell_Excutor/ShellLogger.cpp
  TestShell_Excutor/ShellLogger.h
  TestShell_Excutor/ShellRead.cpp
  TestShell_Excutor/ShellRunner.cpp
  TestShell_Excutor/ShellRunner.h
  TestShell_Excutor/ShellTestScenarios.cpp
  TestShell_Excutor/ShellTestScenarios.h
  TestShell_Excutor/ShellWrite.cpp
  TestShell_Excutor/ShellWrite.h
Labels: Refactor

#154 [add] upload default demo script files
  BoyScoutDemo1-1DayBasic.lst
  BoyScoutDemo2-1DayComplex.lst
  BoyScoutDemo3-3DayExtension.lst
  BoyScoutDemo4-3DayCommandBuffer.lst
  BoyScoutDemo5-TScenarioLoop.lst
  SSD_Project_BoyScout.sln
Labels: Documentation

#173 [refactor] remove warning on build
  TestShell_Excutor/ShellCommand_test.cpp
  TestShell_Excutor/ShellEraseRange.cpp
  TestShell_Excutor/ShellFileUtil.cpp
  TestShell_Excutor/ShellRead.cpp
  TestShell_Excutor/ShellWrite.cpp
Labels: Refactor

#184 [fix] Update presentation file with latest version to prepare PT
  BOYSCOUT_PT.pptx
Labels: Documentation
